### ISSUE TITLE
Play Button Not Working

### ISSUE THREAD

**Issue by sancho1952007** [DonDejvo/dondejvo.github.io#1]
The Play Button Isn't Working In Your Game...
Whenever I Click It, It's Not Clicking.
I Also Clicked The Button via The JS Console Using:
    document.querySelector('#playBtn').click();

But, It Still Didn't Work.
Please See To It...

**Comment by DonDejvo** [comment]
Hello,
I left this game unfinished but what you opened is just menu preview I forgot to remove, you can try the last version on https://dondejvo.github.io/GrottoEscape/index.html, it contains 1 test level :-)

**Comment by sancho1952007** [comment]
> Hello, I left this game unfinished but what you opened is just menu preview I forgot to remove, you can try the last version on https://dondejvo.github.io/GrottoEscape/index.html, it contains 1 test level :-)

OK...
